import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :lets_chat, LetsChatWeb.Endpoint, []

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :lets_chat, LetsChatWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

config :live_vue, ssr_module: LiveVue.SSR.QuickBEAM, ssr: true

# Do not print debug messages in production
config :logger, level: :info

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Disable Swoosh Local Memory Storage
config :swoosh, local: false
