defmodule LetsChat.Repo.Migrations.RoomsLobby do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:rooms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :visibility, :text, null: false, default: "public"
      add :owner_session_id, :text
      add :inserted_at, :timestamptz, null: false, default: fragment("now()")

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "rooms_owner_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing
          )
    end

    create unique_index(:rooms, [:slug], name: "rooms_unique_slug_index")
  end

  def down do
    drop constraint(:rooms, "rooms_owner_user_id_fkey")

    drop_if_exists unique_index(:rooms, [:slug], name: "rooms_unique_slug_index")

    drop table(:rooms)
  end
end
