name: Lets Chat CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: "22.2"
          elixir-version: "1.11"

      - name: Get deps cache
        uses: actions/cache@v1
        with:
         path: deps/
         key: ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}
         restore-keys: ${{ runner.os }}-deps-

      - name: Get build cache
        uses: actions/cache@v1
        with:
          path: _build/test/
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Configures application
        run: mix setup

      - name: Run Lint
        run: mix credo --strict

      - name: Run Tests
        run: mix coveralls.github
